_target_: src.logger.CometMLWriter
project_name: "lcnn-voice-antispoofing"
workspace: null
run_name: "stc-lcnn-fft1724-b32-crop-softweights"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False
id_length: 32 # length of the run_id
